import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const handwrite = localFont({
  src: "../fonts/handwriting.woff2",
  display: "swap",
  variable: "--font-handwrite",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${handwrite.variable}`}
    >
      <body className="dark">{children}</body>
    </html>
  );
}
